---
- hosts: localhost # hostname
  sudo: no
  tasks:

    - name: Taps
      homebrew_tap: tap={{item}}
      with_items:
          - homebrew/versions
          - caskroom/cask
          - caskroom/versions

    - name: Install Basic Components
      homebrew: name={{item}} 
      with_items:
          - vim
          - gcc
          - git
