---
- hosts: localhost # hostname
  sudo: no
  vars:
      ruby_version: "2.1.5"

  tasks:

    - name: Taps
      homebrew_tap: tap={{item}}
      with_items:
          - homebrew/versions
          - caskroom/cask
          - caskroom/versions
          - homebrew/php

    - name: Install GUI Applications
      homebrew_cask: name={{item}}
      with_items:
          - dropbox
          - owncloud
          - iterm2
          - google-japanese-ime
          - bettertouchtool
          - menumeters 
          - karabiner
          - evernote 
          - macvim-kaoriya
          - flash
          - java
          - cyberduck
          - virtualbox
          - vagrant
          - mysqlworkbench
          - bartender
          - vlc
          - rescuetime
          - cocoarestclient
          - adobe-air
          - cacoo-ninja
          - mendeley-desktop
          - github
          - day-o
          - onyx
          - heroku-toolbelt
          - xquartz
          - firefox
          - google-chrome
          - goofy
          - libreoffice
          - kobito
          - duet
          - kindle
          - lastfm
          # - recordit
          # - mactex

    - name: Install Basic Components
      homebrew: name={{item}} 
      with_items:
          - vim
          - cloog
          - gcc
          - pwgen
          - tree
          - git
          - bash
          - trash
          - wget
          - imagemagick
          - ghostscript
          - bash-completion
          - watch
          - nkf
          - nmap
          - awscli
          - ansible
          - postgresql

    - name: Install PHPs
      homebrew: name={{item}}
      with_items:
          - php56
          - composer
          - php56-mcrypt

    - name: Install Rubys
      homebrew: name={{item}}
      with_items: 
          - ruby-build
          - rbenv

    # Install Ruby
    - name: Check Ruby version
      shell: "ruby -v | grep {{ruby_version}}"
      ignore_errors: true
      register: is_correct_version

    - name: Check installed Ruby version
      shell: "rbenv versions | grep {{ruby_version}}"
      ignore_errors: true
      register: ruby_is_installed 
      when: is_correct_version|failed

    - name: Install Ruby
      shell: "rbenv install {{ruby_version}}"
      when: ruby_is_installed|failed

    - name: Switch Ruby version
      shell: "rbenv global {{ruby_version}} && rbenv rehash"
      when: is_correct_version|failed


    - name: Install Gems
      gem: name={{item}} user_install=false
      # user_install=falseで~/.rbenv/...にインストールされる
      with_items:
          - rails
          - bundler
          - chef
          - chef-zero
          - knife-solo
          - berkshelf
          - kitchen-vagrant
          - test-kitchen
          - knife-solo_data_bag
          - serverspec
          - cocoapods
          - tw
        

