---
- hosts: localhost
  sudo: no

  tasks:
      
      - name: Fetch dotfiles
        git: repo=git@github.com:ikuwow/dotfiles.git
             dest=~/dotfiles version=master # "version" is required
