---
# Before execute this, setup github account (set a public key)

- hosts: localhost # hostname
  become: no
  gather_facts: no

- import_playbook: tasks/dotfiles.yml
- import_playbook: tasks/icloud-directories.yml
- import_playbook: tasks/anyenv.yml
- import_playbook: tasks/php.yml
- import_playbook: tasks/system-preferences.yml

