---
# Before execute this, setup github account (set a public key)

- hosts: localhost # hostname
  become: no
  gather_facts: no

  tasks:

    - name: git clone dotfiles
      git: repo=git@github.com:ikuwow/dotfiles.git version=master dest=~/dotfiles
    - name: Bootstrap dotfiles
      shell: "sh ~/dotfiles/make_symlinks.sh"
      args:
        creates: ~/.bashrc

    - name: Taps
      homebrew_tap: tap=homebrew/versions

    - name: Uninstall removed components
      homebrew: name={{item}} state=absent
      with_items:
          - boot2docker
          - docker

    - name: Install Basic Components
      homebrew: name={{item}}
      with_items:
          - ansible
          - awscli
          - bash
          - bash-completion
          - cloog
          - cowsay
          - ctags
          - fortune
          - gcc
          - ghostscript
          - git
          - git-secrets
          - go
          - highlight
          - hugo
          - imagemagick
          - jq
          - libdvdcss # needed by handbrake
          - mysql
          - nkf
          - nmap
          - postgresql
          - pwgen
          - sshrc
          - thefuck
          - tmux
          - trash
          - tree
          - wget
          - watch
          - vim
          - translate-shell
          - gnu-sed
          - gawk

    - name: Check compiler version
      shell: 'ls /usr/local/bin/gcc-* | grep -e "gcc\-[0-9].\?[0-9]\?$" | tail -n 1 | sed -e "s/[a-zA-Z\/\-]//g"'
      changed_when: no
      register: gcc_destver

    - name: Create Path to gcc and g++
      file: src=/usr/local/bin/{{item}}-{{gcc_destver.stdout}} dest=/usr/local/bin/{{item}}
          state=link
      with_items: [gcc, g++]

    - name: Create iCloud Drive Directory
      file: path="~/iCloud Drive" state=directory

    - name: Create iCloud Drive Symlinks
      file: src="~/Library/Mobile Documents/com~apple~{{item}}/Documents"
            dest="~/iCloud Drive/{{item}}" state=link
      with_items:
          - Keynote
          - Numbers
          - Pages
          - Automator
          - Notes
          - Preview
          - TextEdit
          - QuickTimePlayerX
          - ScriptEditor2

    - file: src="~/Library/Mobile Documents/com~apple~CloudDocs"
            dest="~/iCloud Drive/CloudDocs" state=link

- include: tasks/homebrew-cask.yml
- include: tasks/system-preferences.yml
- include: tasks/php.yml
- include: tasks/ruby.yml
- include: tasks/python.yml
- include: tasks/node.yml
- include: tasks/vagrant.yml

