---
- hosts: localhost # hostname
  gather_facts: no
  sudo: no

  tasks:

    # System Language
    - name: Check System Languages
      # not 'command'!
      shell: "defaults read .GlobalPreferences AppleLanguages -array en ja | tr -d '\n' | tr -d ' '"
      register: langs
      changed_when: langs.stdout != '(en,ja)'

    - name: Change System Languages
      shell: "defaults write .GLobalPreferences AppleLanguages -array en ja"
      when: langs.stdout != '(en,ja)'

    # Dock
    - name: Check Dock 
      shell: "defaults read com.apple.dock | grep autohide > /dev/null && test `defaults read com.apple.dock autohide` -eq 1; echo $?"
      register: is_autohide
      changed_when: is_autohide.stdout != '0'

    - name: Autohide Dock
      shell: "defaults write com.apple.dock autohide -int 1"
      notify: Restart Dock
      when: is_autohide.stdout != '0'

    # Trackpad
    - name: Check Tap to Click 
      shell: "test `defaults read com.apple.AppleMultitouchTrackpad Clicking` -eq 1; echo $?"
      register: click_is_active
      changed_when: click_is_active.stdout != '0'

    - name: Enable Tap to Click 
      shell: "defaults write com.apple.AppleMultitouchTrackpad Clicking -int 1"
      when: click_is_active.stdout != '0'

    - name: Check Three finger drag
      shell: "test `defaults read com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag` -eq 1; echo $?"
      register: three_finger_drag
      changed_when: three_finger_drag.stdout != '0'

    - name: Enable Tap to Click 
      shell: "defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -int 1"
      when: three_finger_drag.stdout != '0'

    # Finder
    - name: Check Desktop HardDrives
      shell: "test `defaults read com.apple.finder ShowHardDrivesOnDesktop` -eq 1; echo $?"
      register: shdod
      changed_when: shdod.stdout != '0'

    - name: Show Desktop HardDrives
      shell: "defaults write com.apple.finder ShowHardDrivesOnDesktop -int 1"
      when: shdod.stdout != '0'
      notify: Restart Finder

    - name: Check Show mounted servers
      shell: "test `defaults read com.apple.finder ShowMountedServersOnDesktop` -eq 1; echo $?"
      register: smsod
      changed_when: smsod.stdout != '0'

    - name: Show Mounted Servers
      shell: "defaults write com.apple.finder ShowMountedServersOnDesktop -int 1"
      when: smsod.stdout != '0'
      notify: Restart Finder

    # Safari
    - name: Check DownloadsPath
      shell: "defaults read com.apple.Safari | grep DownloadsPath > /dev/null && test `defaults read com.apple.Safari DownloadsPath` = '~/Desktop'; echo $?"
      register: dlpwc
      changed_when: dlpwc.stdout != '0'

    - name: Change DownloadsPath
      shell: "defaults write com.apple.Safari DownloadsPath -string ~/Desktop && defaults write com.apple.Safari DownloadsPathWasConverted -int 1"
      when: dlpwc.stdout != '0'
      notify: Restart Safari

  handlers:
    - name: Restart Dock
      shell: "killall Dock"
    - name: Restart Finder
      shell: "killall Finder"
    - name: Restart Safari
      shell: "killall Safari && open /Applications/Safari.app"


