---
- hosts: localhost # hostname
  gather_facts: no
  become: no

  tasks:

    - name: Autohide Dock
      osx_defaults: domain=com.apple.dock key=autohide type=int value=1

    - name: Enable Tap to Click
      osx_defaults: domain=com.apple.AppleMultitouchTrackpad key=Clicking type=int value=1

    - name: Show Desktop HardDrives
      osx_defaults: domain=com.apple.finder key=ShowHardDrivesOnDesktop type=bool value=true
      notify: Restart Finder

    - name: Show Mounted Servers
      osx_defaults: domain=com.apple.finder key=ShowMountedServersOnDesktop type=bool value=true
      notify: Restart Finder

    - name: Change DownloadsPath
      osx_defaults: domain=com.apple.Safari key=DownloadsPath value=~/Desktop
      notify: Restart Safari

    - name: Change Display URL
      osx_defaults: domain=com.apple.Safari key=ShowFullURLInSmartSearchField type=bool value=true state=present
      notify: Restart Safari

    - name: Enable Debug Menu
      osx_defaults: domain=com.apple.Safari key=IncludeInternalDebugMenu type=bool value=true state=present
      notify: Restart Safari

  handlers:
    - name: Restart Dock
      shell: "killall Dock"
    - name: Restart Finder
      shell: "killall Finder"
    - name: Restart Safari
      shell: "killall Safari && open /Applications/Safari.app/"

  # And... please install Safari extensions by hand...
  # Pocket, Hatena Bookmark, Adblock Plus, Evernote web clipper, 1password, Format link, etc...

