---
- hosts: localhost 
  sudo: no
  tasks:

    - name: brew upgrade
      homebrew: update_homebrew=yes upgrade_all=yes

    - name: brew cask update
      command: "brew cask update"
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"

    - name: gem update
      shell: "gem update"

    - name: vagrant plugin update
      shell: "vagrant plugin update"


