---

- hosts: localhost
  become: no
  gather_facts: no

  vars:
    envs:
      - pyenv
      - rbenv
      - jenv

  tasks:

    - name: Install anyenv
      git:
        repo: git@github.com:riywo/anyenv.git
        dest: ~/.anyenv

    - name: Remove __env in brew
      homebrew: name={{item}} state=absent
      with_items: "{{envs}}"

    - name: Install envs
      shell: "~/.anyenv/bin/anyenv install {{item}}"
      with_items: "{{envs}}"
      args:
        creates: "~/.anyenv/envs/{{item}}"

