---

- hosts: localhost # hostname
  become: no
  gather_facts: no

  tasks:

    - name: Install nodebrew
      homebrew: name=nodebrew

    - name: Setup nodebrew
      shell: nodebrew setup
      args:
        creates: ~/.nodebrew

