---

- hosts: localhost # hostname
  become: no
  gather_facts: no

  tasks:

    - name: Install Basic Components
      homebrew: name={{item}}
      with_items:
          - node
          - yarn

    - name: Install Node related packages
      npm: name={{item}} global=yes
      with_items:
          - jshint
          - gulp
          - coffee-script
          - elasticsearch-tools

