---

- hosts: localhost # hostname
  become: no
  gather_facts: no
  vars:
      default_node_version: "8.1.3"
      node_path: "$HOME/.nodebrew/current/bin"

  tasks:

    - name: Install nodebrew
      homebrew: name=nodebrew

    - name: Setup nodebrew
      shell: nodebrew setup
      args:
        creates: ~/.nodebrew

    - name: Install default version
      shell: nodebrew install-binary {{default_node_version}}
      args:
        creates: ~/.nodebrew/node/v{{default_node_version}}

    - name: Check current node version
      shell: "nodebrew list | grep current: | sed 's/^current: //g'"
      register: current_node_version
      changed_when: current_node_version.stdout == 'none'

    - name: Set default node version
      shell: |
          nodebrew alias default v{{default_node_version}} \
          && nodebrew use default
      when: current_node_version.stdout == 'none'

    - name: Install npm packages
      npm: name={{item}} global=yes executable={{node_path}}/npm
      with_items:
          - yarn
          - jslint
          - jshint
          - eslint
