---

- hosts: localhost # hostname
  become: no
  gather_facts: no
  vars:
      python_versions:
          - "2.7.13"
          - "3.6.2"

  tasks:

    - name: Install neovim module not using pyenv
      pip:
        executable: /usr/local/bin/pip3
        name: neovim

    - name: Install basic python packages
      homebrew: name=pyenv

    - name: Install Python
      shell: "pyenv install {{item}}"
      environment:
        - CFLAGS: "-I/usr/local/opt/openssl/include"
        - LDFLAGS: "-L/usr/local/opt/openssl/lib"
      args:
        creates: ~/.pyenv/versions/{{item}}/bin/python
      with_items: "{{python_versions}}"

    - name: Is Python in pyenv?
      shell: "which python | grep .pyenv/shims/python > /dev/null; echo $?"
      register: python_is_in_pyenv
      changed_when: python_is_in_pyenv.stdout != '0'

    - name: Switch Python version
      shell: "pyenv global {{python_versions | max}} && pyenv rehash"
      when: python_is_in_pyenv.stdout != '0'

    - name: pyenv init
      shell: 'eval "$(pyenv init -)"'
      changed_when: python_is_in_pyenv.stdout != '0'
