---

- name: Install Rubys
  homebrew: name={{item}}
  with_items:
      - ruby-build
      - rbenv

- name: Install Ruby
  shell: "rbenv install {{base_ruby_version}}"
  args:
    creates: ~/.rbenv/versions/{{base_ruby_version}}/bin/ruby

- name: Is ruby in rbenv?
  shell: "which ruby | grep .rbenv/shims/ruby > /dev/null; echo $?"
  register: ruby_is_in_rbenv
  changed_when: ruby_is_in_rbenv.stdout != '0'

- name: Switch Ruby version
  shell: "rbenv global {{base_ruby_version}} && rbenv rehash"
  when: ruby_is_in_rbenv.stdout != '0'

- name: rbenv init
  shell: 'eval "$(rbenv init -)"'
  changed_when: ruby_is_in_rbenv.stdout != '0'

- name: Install Gems
  gem: name={{item}} user_install=false
  # user_install=falseで~/.rbenv/...にインストールされる
  with_items:
      - rails
      - bundler
      - serverspec
      - cocoapods
      - tw

- name: Uninstall gems
  gem: name={{item}} user_install=false state=absent
  with_items:
      - chef
      - chef-zero
      - knife-solo
      - berkshelf
      - kitchen-vagrant
      - test-kitchen
      - knife-solo_data_bag
      - i2cssh

