---

- hosts: localhost # hostname
  become: no
  gather_facts: no
  vars:
      ruby_versions:
        - "2.2.8"
        - "2.3.5"
        - "2.4.2"

  tasks:
    - name: Install Rubys
      homebrew: name={{item}}
      with_items:
          - ruby-build
          - rbenv

    - name: Install Ruby
      shell: "rbenv install {{item}}"
      args:
        creates: ~/.rbenv/versions/{{item}}/bin/ruby
      with_items: "{{ruby_versions}}"

    - name: Is ruby in rbenv?
      shell: "which ruby | grep .rbenv/shims/ruby > /dev/null; echo $?"
      register: ruby_is_in_rbenv
      changed_when: ruby_is_in_rbenv.stdout != '0'

    - name: Switch Ruby version
      shell: "rbenv global {{ruby_versions | max}} && rbenv rehash"
      when: ruby_is_in_rbenv.stdout != '0'

    - name: rbenv init
      shell: 'eval "$(rbenv init -)"'
      changed_when: ruby_is_in_rbenv.stdout != '0'

    - name: Install Gems
      gem: name={{item}} user_install=false
      # user_install=falseで~/.rbenv/...にインストールされる
      with_items:
          - rails
          - bundler
          - serverspec
          - cocoapods
          - tw
          - compass

    - name: Uninstall gems
      gem: name={{item}} user_install=false state=absent
      with_items:
          - chef
          - chef-zero
          - knife-solo
          - berkshelf
          - kitchen-vagrant
          - test-kitchen
          - knife-solo_data_bag
          - i2cssh

