---

- hosts: localhost # hostname
  become: no
  gather_facts: no

  tasks:

   - name: List Installed Vagrant Plugins
     shell: "vagrant plugin list | awk '{ print $1 }'"
     changed_when: false
     register: vagrant_plugin_list

   - name: Install Vagrant Plugins
     shell: "vagrant plugin install {{item}}"
     with_items:
       - vagrant-omnibus
       - vagrant-vbguest
       - vagrant-cachier
       - vagrant-vbox-snapshot
       - vagrant-aws
       - vagrant-digitalocean
     when: item not in vagrant_plugin_list.stdout_lines

