---

- name: Is Go in goenv?
  shell: "which go | grep .goenv/shims/go > /dev/null; echo $?"
  register: go_is_in_goenv
  changed_when: go_is_in_goenv.stdout != '0'

- name: goenv init
  shell: 'eval "$({{anyenv_install_path}}/envs/goenv/bin/goenv init -)"'
  changed_when: go_is_in_goenv.stdout != '0'

- name: Install Gos
  shell: |
    eval "$({{anyenv_install_path}}/envs/goenv/bin/goenv init -)"
    {{anyenv_install_path}}/envs/goenv/bin/goenv install {{item}}
  args:
    creates: "{{anyenv_install_path}}/envs/goenv/versions/{{item}}/bin/go"
  with_items: "{{go_versions}}"

- name: Switch go version
  shell: "{{anyenv_install_path}}/envs/goenv/bin/goenv global {{go_versions | max}} && {{anyenv_install_path}}/envs/goenv/bin/goenv rehash"
  when: go_is_in_goenv.stdout != '0'
