---
- name: Install javas
  homebrew_cask: name={{item}}
  with_items:
    - java # oracle java 9
    - java8 # oracle java 8

- name: Add javas
  shell: jenv add $(/usr/libexec/java_home -v {{item}})
  args:
    creates: "{{anyenv_install_path}}/envs/jenv/versions/{{item}}/bin/java"
  with_items: "{{java_versions}}"

- name: Add java-related packages
  homebrew: name={{item}}
  with_items:
    - maven
    - tomcat

- name: Tap java dependency's tap
  homebrew_tap: tap=pivotal/tap

- name: Install springboot
  homebrew: name=springboot

- name: Install jvm languages
  homebrew: name={{item}}
  with_items:
    - scala

- name: Add jenv plugins
  shell: eval "$(jenv init -)" && jenv enable-plugin {{item}}
  register: result
  changed_when: '"plugin already enabled" not in result.stdout'
  with_items:
    - groovy
    - maven

