---

- name: Is Node in ndenv?
  shell: "which node | grep .ndenv/shims/node > /dev/null; echo $?"
  register: node_is_in_ndenv
  changed_when: node_is_in_ndenv.stdout != '0'

- name: ndenv init
  shell: 'eval "$({{anyenv_install_path}}/envs/ndenv/bin/ndenv init -)"'
  changed_when: node_is_in_ndenv.stdout != '0'

- name: Install Node
  shell: "{{anyenv_install_path}}/envs/ndenv/bin/ndenv install {{item}}"
  args:
    creates: "{{anyenv_install_path}}/envs/ndenv/versions/{{item}}/bin/node"
  with_items: "{{node_versions}}"

- name: Switch Node version
  shell: "{{anyenv_install_path}}/envs/ndenv/bin/ndenv global {{node_versions | max}} && {{anyenv_install_path}}/envs/ndenv/bin/ndenv rehash"
  when: node_is_in_ndenv.stdout != '0'

